---

- name: ngxapp systemd unit
  template: src=templates/ngxapp.service.j2 dest=/etc/systemd/system/ngxapp.service owner=root group=root mode=0644

- name: ngxapp conf dir
  file: path=/etc/apps state=directory mode=0755 owner=root group=root

- name: ngxapp config file
  template: src=templates/ngxapp_nginx.conf.j2 dest=/etc/apps/ngxapp_nginx.conf owner=root group=root mode=0644

- name: ngxapp systemd unit start
  systemd:
    daemon_reload: yes
    name: ngxapp.service
    state: started
    enabled: yes
    masked: no
